spring:
  application:
    name: vets-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server.spring-clinic.svc.cluster.local:8888}
    fail-fast: true
    retry:
      initial-interval: 1000
      max-interval: 2000
      max-attempts: 20
  cache:
    cache-names: vets
  profiles:
    active: production
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://clinic-staging-discovery.spring-clinic-staging.svc.cluster.local:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888