spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server.spring-clinic-staging.svc.cluster.local:8888}
    fail-fast: true
    retry:
      initial-interval: 1000
      max-interval: 2000
      max-attempts: 20
  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
        - name: Retry
          args:
            retries: 1
            statuses: SERVICE_UNAVAILABLE
            methods: POST
      routes:
        - id: vets-service
          uri: lb://vets-service.spring-clinic.svc.cluster.local
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: lb://visits-service.spring-clinic.svc.cluster.local
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: lb://customers-service.spring-clinic.svc.cluster.local
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: genai-service
          uri: lb://genai-service.spring-clinic.svc.cluster.local
          predicates:
            - Path=/api/genai/**
          filters:
            - StripPrefix=2
            - CircuitBreaker=name=genaiCircuitBreaker,fallbackUri=/fallback

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888