spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server.spring-clinic.svc.cluster.local:8888}
    fail-fast: true
    retry:
      initial-interval: 1000
      max-interval: 2000
      max-attempts: 20
  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
            statusCodes: 500,503,504
        - name: Retry
          args:
            retries: 3
            statuses: SERVICE_UNAVAILABLE,INTERNAL_SERVER_ERROR
            methods: GET,POST
            backoff:
              firstBackoff: 1000ms
              maxBackoff: 5000ms
              factor: 2
              basedOnPreviousValue: false
      routes:
        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
            - name: Retry
              args:
                retries: 3
                statuses: SERVICE_UNAVAILABLE
                methods: GET,POST
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: customersCircuitBreaker
                fallbackUri: forward:/customers-fallback
                statusCodes: 503,500
            - name: Retry
              args:
                retries: 3
                statuses: SERVICE_UNAVAILABLE
                methods: GET,POST
                exceptions:
                  - org.springframework.web.server.ResponseStatusException
        - id: genai-service
          uri: lb://genai-service
          predicates:
            - Path=/api/genai/**
          filters:
            - StripPrefix=2
            - CircuitBreaker=name=genaiCircuitBreaker,fallbackUri=/fallback
  client:
    serviceUrl:
      defaultZone: http://clinic-staging-discovery.spring-clinic-staging.svc.cluster.local:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  http:
    connection:
      timeout: 5000
    read:
      timeout: 5000
    write:
      timeout: 5000
  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    circuitbreakers:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.retry: DEBUG
    org.springframework.cloud.circuitbreaker: DEBUG

---
spring:
  config:
    activate:
      on-profile: kubernetes
    import: configserver:http://config-server.spring-clinic.svc.cluster.local:8888
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server.spring-clinic.svc.cluster.local:8888