spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server.spring-clinic.svc.cluster.local:8888}
    fail-fast: true
    retry:
      initial-interval: 1000
      max-interval: 2000
      max-attempts: 20
  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
        - name: Retry
          args:
            retries: 1
            statuses: SERVICE_UNAVAILABLE
            methods: POST
      routes:
        - id: clinic-staging-vets
          uri: http://clinic-staging-vets.spring-clinic-staging.svc.cluster.local:8083
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: clinic-staging-visits
          uri: http://clinic-staging-visits.spring-clinic-staging.svc.cluster.local:8082
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: clinic-staging-customer
          uri: http://clinic-staging-customer.spring-clinic-staging.svc.cluster.local:8081
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: clinic-staging-genai
          uri: http://clinic-staging-genai.spring-clinic-staging.svc.cluster.local:8084
          predicates:
            - Path=/api/genai/**
          filters:
            - StripPrefix=2
            - CircuitBreaker=name=genaiCircuitBreaker,fallbackUri=/fallback
eureka:
  client:
    serviceUrl:
      defaultZone: http://clinic-staging-discovery.spring-clinic-staging.svc.cluster.local:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
---
spring:
  config:
    activate:
      on-profile: kubernetes
    import: configserver:http://config-server.spring-clinic.svc.cluster.local:8888
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server.spring-clinic.svc.cluster.local:8888