server:
  port: 8761
spring:
  application:
    name: clinic-staging-discovery
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server.spring-clinic.svc.cluster.local:8888}
    fail-fast: true
    retry:
      initial-interval: 1000
      max-interval: 2000
      max-attempts: 20
eureka:
  instance:
    hostname: http://clinic-staging-apigateway.spring-clinic.svc.cluster.local:8761
    nonSecurePort: 8761
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://clinic-staging-discovery.spring-clinic-staging.svc.cluster.local:8761/eureka/
  server:
    enableSelfPreservation: true
    enable-replicated: false
    peerNodeReadTimeoutMs: 10000
    peerEurekaNodesUpdateIntervalMs: 60000
---
spring:
  config:
    activate:
      on-profile: kubernetes
    import: configserver:http://config-server.spring-clinic-staging.svc.cluster.local:8888
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server.spring-clinic-staging.svc.cluster.local:8888