spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server.spring-clinic.svc.cluster.local:8888}
    fail-fast: true
    retry:
      initial-interval: 10000
      max-interval: 20000
      max-attempts: 200

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:discovery-server.spring-clinic.svc.cluster.local}:${EUREKA_SERVER_PORT:8761}/eureka/
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.85
    peer-node-read-timeout-ms: 10000

logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888