{{- if .Values.services.config.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-config
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: config-server
    component: config-server
spec:
  replicas: {{ .Values.services.config.replicaCount }}
  strategy:
    type: {{ .Values.services.config.strategy.type | default "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.services.config.strategy.rollingUpdate.maxSurge | default "25%" }}
      maxUnavailable: {{ .Values.services.config.strategy.rollingUpdate.maxUnavailable | default "25%" }}
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
        component: config-server
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      tolerations: {{ $.Values.global.tolerations | toYaml | nindent 8 }}
      containers:
        - name: config-server
          image: "{{ .Values.services.config.image.repository }}:{{ .Values.services.config.image.tag }}"
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.services.config.containerPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: {{ .Values.services.config.gitUri | quote }}
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS
              value: {{ `{application}` | quote }}  # Đã sửa ở đây
          resources:
            {{- toYaml .Values.services.config.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.services.config.containerPort }}
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.services.config.containerPort }}
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.services.config.containerPort }}
            failureThreshold: 30
            periodSeconds: 10
{{- end }}