{{- if .Values.services.config.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-config
  namespace: spring-clinic  # Cố định namespace cho config-server
  labels:
    app: config-server
    component: config-server
spec:
  replicas: {{ .Values.services.config.replicaCount }}
  strategy:
    type: {{ .Values.services.config.strategy.type | default "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.services.config.strategy.rollingUpdate.maxSurge | default "25%" }}
      maxUnavailable: {{ .Values.services.config.strategy.rollingUpdate.maxUnavailable | default "25%" }}
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
        component: config-server
      annotations:
        checksum/config: {{ toYaml .Values | sha256sum }}
    spec:
      tolerations: {{ $.Values.global.tolerations | toYaml | nindent 8 }}
      containers:
        - name: config-server
          image: "{{ .Values.services.config.image.repository }}:{{ .Values.services.config.image.tag }}"
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.services.config.containerPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: {{ .Values.services.config.gitUri | quote }}
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS
              value: {{ `{application}` | quote }}
          resources:
            {{- toYaml .Values.services.config.resources | nindent 12 }}
{{- end }}

{{- range $key, $value := .Values.services }}
{{- if $value.enabled }}
{{- if ne $key "config" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $key }}
  namespace: {{ $.Values.global.namespace }}  # Các dịch vụ khác dùng global.namespace
  labels:
    app: {{ $key }}
    component: {{ $key }}
spec:
  replicas: {{ $value.replicaCount }}
  strategy:
    type: {{ $value.strategy.type | default "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ $value.strategy.rollingUpdate.maxSurge | default "25%" }}
      maxUnavailable: {{ $value.strategy.rollingUpdate.maxUnavailable | default "25%" }}
  selector:
    matchLabels:
      app: {{ $key }}
  template:
    metadata:
      labels:
        app: {{ $key }}
        component: {{ $key }}
      annotations:
        checksum/config: {{ toYaml $.Values | sha256sum }}
    spec:
      tolerations: {{ $.Values.global.tolerations | toYaml | nindent 8 }}
      containers:
        - name: {{ $key }}
          image: "{{ $value.image.repository }}:{{ $value.image.tag }}"
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ $value.containerPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SPRING_CLOUD_CONFIG_SERVER_URI
              value: {{ $.Values.global.configServer.url | quote }}
          resources:
            {{- toYaml $value.resources | nindent 12 }}
{{- end }}
{{- end }}
{{- end }}