{{- range $key, $value := .Values.services }}
{{- if $value.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $key }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ if eq $key "config" }}config-server{{ else }}{{ $key }}{{ end }}
spec:
  replicas: {{ $value.replicaCount }}
  strategy:
    type: {{ $value.strategy.type }}
    rollingUpdate:
      maxSurge: {{ $value.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ $value.strategy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ if eq $key "config" }}config-server{{ else }}{{ $key }}{{ end }}
  template:
    metadata:
      labels:
        app: {{ if eq $key "config" }}config-server{{ else }}{{ $key }}{{ end }}
    spec:
      tolerations: {{ $.Values.global.tolerations | toYaml | nindent 8 }}
      containers:
        - name: {{ $key }}
          image: "{{ $value.image.repository }}:{{ $value.image.tag }}"
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ $value.containerPort }}
          resources:
            {{- toYaml $value.resources | nindent 12 }}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: {{ if eq $key "config" }}config-server{{ else }}{{ $.Release.Name }}-{{ $key }}{{ end }}.{{ $.Values.global.namespace }}.svc.cluster.local
{{- end }}
{{- end }}
