{{- if .Values.apigateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-apigateway
  namespace: {{ .Values.global.namespace }}
  labels:
    app: api-gateway
    component: api-gateway
spec:
  replicas: {{ .Values.apigateway.replicaCount | default 1 }}
  revisionHistoryLimit: {{ .Values.apigateway.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        component: api-gateway
        env: {{ .Values.apigateway.env | default "staging" }}
      annotations:
        checksum/config: {{ toYaml .Values | sha256sum }}
    spec:
      tolerations: {{ .Values.global.tolerations | toYaml | nindent 8 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: env
                      operator: In
                      values:
                        - {{ .Values.apigateway.env | default "staging" }}
                topologyKey: kubernetes.io/hostname
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: api-gateway
          image: {{ .Values.apigateway.image.repository }}:{{ .Values.apigateway.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.apigateway.containerPort }}
              name: http
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          resources:
            {{- toYaml .Values.apigateway.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/application.properties
              subPath: application.properties
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.configMap.name }}
            defaultMode: 420
{{- end }}