{{- range $key, $value := .Values.services }}
{{- if $value.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $key }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $key }}
spec:
  selector:
    app: {{ $key }}
  ports:
  - protocol: TCP
    port: {{ $value.service.port }}
    targetPort: {{ $value.service.targetPort }}
  type: {{ $value.service.type }}
{{- end }}
{{- end }}