apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: visits-service-hpa
  namespace: spring-clinic
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: visits-service-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70