spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  zipkin:
    base-url: http://clinic-staging-zipkin.spring-clinic-staging.svc.cluster.local:9411
    enabled: true

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
