spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server.spring-clinic.svc.cluster.local:8888}
    fail-fast: true
    retry:
      initial-interval: 10000
      max-interval: 20000
      max-attempts: 200

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888