global:
  namespace: spring-clinic
  imagePullPolicy: IfNotPresent
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  configServer:
    url: "http://config-server:8888"
    enabled: true
services:
  admin:
    enabled: true
    replicaCount: 1
    image:
      repository: ktei8htop15122004/clinic-microservices
      tag: "admin-server-b15c163"
    containerPort: 9090
    service:
      type: ClusterIP
      port: 9090
      targetPort: 9090
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 25%
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 90

  apigateway:
    enabled: true
    replicaCount: 1
    image:
      repository: ktei8htop15122004/clinic-microservices
      tag: "api-gateway-8c42434"
    containerPort: 8080
    service:
      type: ClusterIP
      port: 8080
      targetPort: 8080
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 25%
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 90

  config:
    gitUri: https://github.com/KhacThien88/config-server-clinic.git
    enabled: true
    replicaCount: 1
    image:
      repository: ktei8htop15122004/clinic-microservices
      tag: "config-server-b30653a"
    containerPort: 8888
    service:
      type: ClusterIP
      port: 8888
      targetPort: 8080
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 25%

  customer:
    enabled: true
    replicaCount: 1
    image:
      repository: ktei8htop15122004/clinic-microservices
      tag: "customers-service-b264909"
    containerPort: 8081
    service:
      type: ClusterIP
      port: 8081
      targetPort: 8081
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 25%
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 90

  discovery:
    enabled: true
    replicaCount: 1
    image:
      repository: ktei8htop15122004/clinic-microservices
      tag: "discovery-server-e798e73"
    containerPort: 8761
    service:
      type: ClusterIP
      port: 8761
      targetPort: 8761
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 25%
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 90

  genai:
    enabled: true
    replicaCount: 1
    image:
      repository: ktei8htop15122004/clinic-microservices
      tag: "genai-service-8bbfae3"
    containerPort: 8084
    service:
      type: ClusterIP
      port: 8084
      targetPort: 8084
    resources:
      requests:
        memory: "256Mi"
        cpu: "256m"
      limits:
        memory: "256Mi"
        cpu: "256m"
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 25%
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 90

  vets:
    enabled: true
    replicaCount: 1
    image:
      repository: ktei8htop15122004/clinic-microservices
      tag: "vets-service-951d802"
    containerPort: 8083
    service:
      type: ClusterIP
      port: 8083
      targetPort: 8083
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 25%
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 90

  visits:
    enabled: true
    replicaCount: 1
    image:
      repository: ktei8htop15122004/clinic-microservices
      tag: "visits-service-f84808b"
    containerPort: 8082
    service:
      type: ClusterIP
      port: 8082
      targetPort: 8082
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 25%
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 90
  
spec:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

ingress:
  enabled: true
  ingressClassName: nginx
  rules:
    - host: "testenv-pet-clinic.khacthienit.click"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apigateway
                port:
                  number: 8080