global:
  namespace: spring-clinic
  imagePullPolicy: IfNotPresent
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  configServer:
    url: "http://config-server:8888"
    enabled: true
services:
  admin:
    enabled: true
    replicaCount: 2
    image:
      repository: ktei8htop15122004/clinic-microservices
      tag: "admin-server-98e7ea3"
    containerPort: 9090
    service:
      type: ClusterIP
      port: 80
      targetPort: 9090
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "150Mi"
        cpu: "150m"
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 25%
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 70

  apigateway:
    enabled: true
    replicaCount: 2
    image:
      repository: ktei8htop15122004/clinic-microservices
      tag: "api-gateway-b741caa"
    containerPort: 8080
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "150Mi"
        cpu: "150m"
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 25%
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 70

  config:
    gitUri: https://github.com/KhacThien88/config-server-clinic.git
    enabled: true
    replicaCount: 2
    image:
      repository: ktei8htop15122004/clinic-microservices
      tag: "config-server-169c8a6"
    containerPort: 8888
    service:
      type: ClusterIP
      port: 8888
      targetPort: 8888
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "250m"
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 25%
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 70

  customer:
    enabled: true
    replicaCount: 2
    image:
      repository: ktei8htop15122004/clinic-microservices
      tag: "customers-service-6bd487f"
    containerPort: 8081
    service:
      type: ClusterIP
      port: 80
      targetPort: 8081
    resources:
      requests:
        memory: "100Mi"
        cpu: "125m"
      limits:
        memory: "150Mi"
        cpu: "150m"
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 25%
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 70

  discovery:
    enabled: true
    replicaCount: 2
    image:
      repository: ktei8htop15122004/clinic-microservices
      tag: "discovery-server-3691f6b"
    containerPort: 8761
    service:
      type: ClusterIP
      port: 80
      targetPort: 8761
    resources:
      requests:
        memory: "100Mi"
        cpu: "125m"
      limits:
        memory: "150Mi"
        cpu: "150m"
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 25%
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 70

  genai:
    enabled: true
    replicaCount: 2
    image:
      repository: ktei8htop15122004/clinic-microservices
      tag: "genai-service-2910f8c"
    containerPort: 8084
    service:
      type: ClusterIP
      port: 80
      targetPort: 8084
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "150Mi"
        cpu: "150m"
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 25%
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 70

  vets:
    enabled: true
    replicaCount: 2
    image:
      repository: ktei8htop15122004/clinic-microservices
      tag: "vets-service-2cadb97"
    containerPort: 8083
    service:
      type: ClusterIP
      port: 80
      targetPort: 8083
    resources:
      requests:
        memory: "125Mi"
        cpu: "125m"
      limits:
        memory: "150Mi"
        cpu: "150m"
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 25%
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 70

  visits:
    enabled: true
    replicaCount: 2
    image:
      repository: ktei8htop15122004/clinic-microservices
      tag: "visits-service-938308a"
    containerPort: 8082
    service:
      type: ClusterIP
      port: 80
      targetPort: 8082
    resources:
      requests:
        memory: "125Mi"
        cpu: "125m"
      limits:
        memory: "150Mi"
        cpu: "150m"
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 50%
        maxUnavailable: 25%
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 70
spec:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

ingress:
  enabled: true
  ingressClassName: nginx
  rules:
    - host: "testenv-pet-clinic.khacthienit.click"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apigateway
                port:
                  number: 80