spring:
  zipkin:
    base-url: http://clinic-staging-zipkin.spring-clinic-staging.svc.cluster.local:9411
    enabled: true
  profiles:
    active: kubernetes
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KhacThien88/config-server-clinic
          clone-on-start: true
          default-label: main