server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KhacThien88/config-server-clinic
          default-label: main
          search-paths: '{application}'  # Thêm dòng này nếu cần
          clone-on-start: true  # Thêm dòng này để clone ngay khi khởi động