spring:
  config:
    activate:
      on-profile: kubernetes
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/KhacThien88/config-server-clinic.git"
          default-label: main
          search-paths: '{application}'
          clone-on-start: true