apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-deployment
  namespace: spring-clinic
  labels:
    app: tracing
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: tracing
  template:
    metadata:
      labels:
        app: tracing
    spec:
      containers:
      - name: tracing
        image: openzipkin/zipkin
        ports:
        - containerPort: 8888
        resources:
          requests:
            memory: "125Mi"
            cpu: "125m"
          limits:
            memory: "250Mi"
            cpu: "250m"