apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-deployment
  namespace: spring-clinic
  labels:
    app: customer-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: springcommunity/spring-petclinic-customers-service
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "125Mi"
            cpu: "125m"
          limits:
            memory: "250Mi"
            cpu: "250m"