apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service-deployment
  namespace: spring-clinic
  labels:
    app: genai-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: genai-service
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      containers:
      - name: genai-service
        image: springcommunity/spring-petclinic-genai-service
        ports:
        - containerPort: 8084
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "300Mi"
            cpu: "300m"