apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: spring-clinic
  labels:
    app: genai-service
spec:
  selector:
    app: genai-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: ClusterIP