apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: spring-clinic
  labels:
    app: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: ClusterIP