apiVersion: v1
kind: Service
metadata:
  name: visits-service
  namespace: spring-clinic
  labels:
    app: visits-service
spec:
  selector:
    app: visits-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP