apiVersion: v1
kind: Service
metadata:
  name: tracing-service
  namespace: spring-clinic
  labels:
    app: tracing-service
spec:
  selector:
    app: tracing-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9411
  type: ClusterIP