apiVersion: v1
kind: Service
metadata:
  name: vets-service
  namespace: spring-clinic
  labels:
    app: vets-service
spec:
  selector:
    app: vets-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: ClusterIP