apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: spring-clinic
  labels:
    app: customer-service
spec:
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP