apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: spring-clinic
  labels:
    app: discovery-service
spec:
  selector:
    app: discovery-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
  type: ClusterIP